version: '3.1'

services:
  db:
    image: postgres:12.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_postgres:/var/lib/postgres
      - ./docker-init/postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  db_postgres:
    driver: local
